/**
 * smartTruncator.ts
 * Safely truncates very large files while preserving the most semantically
 * important sections (imports, class/function signatures, exports).
 */

import { estimateTokens } from './tokenCounter';

export interface TruncationResult {
  content: string;
  wasTruncated: boolean;
  originalTokens: number;
  truncatedTokens: number;
  strategy: string;
}

/** Token threshold above which we consider a file "large" */
const LARGE_FILE_THRESHOLD = 4_000;
/** Hard cap for a single file in AI_MAX mode */
const HARD_CAP_TOKENS = 8_000;

/**
 * Truncate a file intelligently:
 * 1. Keep all imports/requires
 * 2. Keep all function/class/interface signatures (bodies stripped in aggressive mode)
 * 3. Keep the first N lines of each function body
 * 4. Append a summary marker
 */
export function smartTruncate(
  content: string,
  ext: string,
  maxTokens: number = LARGE_FILE_THRESHOLD,
  aggressive: boolean = false
): TruncationResult {
  const originalTokens = estimateTokens(content);

  if (originalTokens <= maxTokens) {
    return {
      content,
      wasTruncated: false,
      originalTokens,
      truncatedTokens: originalTokens,
      strategy: 'none',
    };
  }

  const lines = content.split('\n');
  const kept: string[] = [];
  let strategy = 'tail-cut';

  if (aggressive && originalTokens > HARD_CAP_TOKENS) {
    // Aggressive: extract only signatures + first few lines of each body
    const result = extractSignatures(lines, ext);
    kept.push(...result.lines);
    strategy = 'signature-extract';
  } else {
    // Conservative: keep top portion + tail summary
    const targetLines = Math.floor(lines.length * (maxTokens / originalTokens) * 0.9);
    kept.push(...lines.slice(0, targetLines));
    strategy = 'tail-cut';
  }

  const truncatedLines = estimateTokens(kept.join('\n'));
  const omitted = originalTokens - truncatedLines;

  kept.push('');
  kept.push(`// [PyPoints Truncation: ~${omitted} tokens omitted. Strategy: ${strategy}. Full file has ${lines.length} lines.]`);

  const truncatedContent = kept.join('\n');

  return {
    content: truncatedContent,
    wasTruncated: true,
    originalTokens,
    truncatedTokens: estimateTokens(truncatedContent),
    strategy,
  };
}

interface SignatureExtractionResult {
  lines: string[];
  signaturesFound: number;
}

/** Extract only the structural skeleton of a file (signatures + short bodies) */
function extractSignatures(lines: string[], ext: string): SignatureExtractionResult {
  const result: string[] = [];
  let signaturesFound = 0;

  const isImport = (l: string) =>
    /^\s*(import|from|require|export\s+(default\s+)?(\{|type|interface|class|function|const|let|var))/.test(l);

  const isFunctionSig = (l: string) =>
    /^\s*(export\s+)?(async\s+)?(function|def|class|interface|type|const\s+\w+\s*=\s*(async\s+)?\()/.test(l);

  const isClassMember = (l: string) =>
    /^\s+(public|private|protected|static|async|override|abstract)?\s*(constructor|get|set|\w+\s*\()/.test(l);

  let inBody = false;
  let bodyLineCount = 0;
  const MAX_BODY_LINES = 3;

  for (const line of lines) {
    if (isImport(line)) {
      result.push(line);
      continue;
    }

    if (isFunctionSig(line) || isClassMember(line)) {
      signaturesFound++;
      result.push(line);
      inBody = true;
      bodyLineCount = 0;
      continue;
    }

    if (inBody) {
      if (bodyLineCount < MAX_BODY_LINES) {
        result.push(line);
        bodyLineCount++;
      } else if (bodyLineCount === MAX_BODY_LINES) {
        result.push(`  // ... (body truncated)`);
        bodyLineCount++;
      }
      // Continue until we see a new top-level signature
      if (isFunctionSig(line) && bodyLineCount > MAX_BODY_LINES) {
        inBody = false;
        bodyLineCount = 0;
        result.push(line);
        signaturesFound++;
      }
      continue;
    }

    // Keep decorator lines and type annotations
    if (/^\s*@\w+/.test(line) || /^\s*(type|interface|enum)\s+\w+/.test(line)) {
      result.push(line);
    }
  }

  return { lines: result, signaturesFound };
}

/**
 * Detect if a file is likely auto-generated (should be excluded or heavily truncated).
 */
export function isGeneratedFile(content: string, filename: string): boolean {
  // Check filename patterns
  const generatedPatterns = [
    /\.min\.(js|css)$/i,
    /\.bundle\.(js|css)$/i,
    /\.generated\./i,
    /\.d\.ts$/,
    /package-lock\.json$/,
    /yarn\.lock$/,
    /pnpm-lock\.yaml$/,
    /composer\.lock$/,
    /Podfile\.lock$/,
  ];

  if (generatedPatterns.some(p => p.test(filename))) return true;

  // Check content markers (first 500 chars)
  const head = content.slice(0, 500);
  const generatedMarkers = [
    '@generated',
    '// Generated by',
    '/* Generated by',
    '# Generated by',
    'DO NOT EDIT',
    'This file is auto-generated',
    '// <auto-generated>',
    'AUTOGENERATED',
  ];

  return generatedMarkers.some(m => head.includes(m));
}

/**
 * Detect if a file is likely a minified file (very long lines, no newlines).
 */
export function isMinifiedFile(content: string): boolean {
  const lines = content.split('\n');
  if (lines.length === 0) return false;

  // If average line length is very high, it's probably minified
  const avgLineLen = content.length / lines.length;
  return avgLineLen > 500;
}